# Numpy

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

## Informações sobre a array

In [2]:
# Numpy arrays possuem alguns atributos que fornecem informações sobre 
# suas características
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]])
print("Formato do array = ", a.shape)
print("Número de dimensões = ", a.ndim)
print("Número de elementos = ", a.size)
print("Tamanho em bytes = ", a.nbytes)
print("Tipo de cada elemento = ", a.dtype)

Formato do array =  (3, 4)
Número de dimensões =  2
Número de elementos =  12
Tamanho em bytes =  96
Tipo de cada elemento =  int64


In [3]:
# Os tipos mais comuns de elementos são inteiros (de vários tamanhos),
# floats e booleanos
b = np.array([[True, False, False], [False, True, False]])
print("Tipo do elemento de b = ", b.dtype)

Tipo do elemento de b =  bool


In [4]:
# Podemos forçar que a array seja criada com um determinado tipo
# usando o parâmetro dtype do construtor da array
c = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]], dtype="float64")
print("Tamanho em bytes = ", c.nbytes)
print("Tipo de cada elemento = ", c.dtype)

Tamanho em bytes =  96
Tipo de cada elemento =  float64


In [5]:
# Alguns atributos se comportam como funções.  Por exemplo, para 
# obter a parte imaginária dos elementos de uma array, use o
# atributo imag
a = np.array([[0, 1j, 2j], [0, 2j, 1j]])
c = np.exp(a*np.pi/3)
print("c = \n", c)
print("Parte imaginária de c = \n", c.imag)
print("Parte real de c = \n", c.real)

c = 
 [[ 1. +0.j         0.5+0.8660254j -0.5+0.8660254j]
 [ 1. +0.j        -0.5+0.8660254j  0.5+0.8660254j]]
Parte imaginária de c = 
 [[0.        0.8660254 0.8660254]
 [0.        0.8660254 0.8660254]]
Parte real de c = 
 [[ 1.   0.5 -0.5]
 [ 1.  -0.5  0.5]]


In [6]:
# Um outro atributo-função é o atributo T, que transpõe um array
print("Transposta de c = \n", c.T)

Transposta de c = 
 [[ 1. +0.j         1. +0.j       ]
 [ 0.5+0.8660254j -0.5+0.8660254j]
 [-0.5+0.8660254j  0.5+0.8660254j]]


In [7]:
# Note que numpy raramente copia um array
print(a)
a.imag[0, 0] = 2
print(a)
a.T[2, 1] = 2
print(a)

[[0.+0.j 0.+1.j 0.+2.j]
 [0.+0.j 0.+2.j 0.+1.j]]
[[0.+2.j 0.+1.j 0.+2.j]
 [0.+0.j 0.+2.j 0.+1.j]]
[[0.+2.j 0.+1.j 0.+2.j]
 [0.+0.j 0.+2.j 2.+0.j]]


## Manipulando arrays

In [8]:
# Podemos redimensionar um array usando a função resize()
a = np.array([[0, 1], [2, 3]])
print("Array a antes de redimensionar:\n", a)
a.resize(2, 4)
print("Array a depois de redimensionar:\n", a)

Array a antes de redimensionar:
 [[0 1]
 [2 3]]
Array a depois de redimensionar:
 [[0 1 2 3]
 [0 0 0 0]]


In [9]:
# Observe que a forma de ordenar os elementos de uma matriz (C-like
# ou Fortran-like) influencia no resultado
b = np.array([[0, 1], [2, 3]], order="F")
print("Array b antes de redimensionar:\n", b)
b.resize(2, 4)
print("Array b depois de redimensionar:\n", b)

Array b antes de redimensionar:
 [[0 1]
 [2 3]]
Array b depois de redimensionar:
 [[0 1 0 0]
 [2 3 0 0]]


In [10]:
# Podemos converter um array qualquer para um array unidimensional através
# dos métodos flatten() ou ravel(). Ambos os métodos são similares
c = a.ravel()
print("Array c:\n", c)
d = a.flatten()
print("Array d:\n", d)

Array c:
 [0 1 2 3 0 0 0 0]
Array d:
 [0 1 2 3 0 0 0 0]


In [11]:
# O método flatten(), entretanto, produz uma cópia da array, enquanto
# ravel() não
a[-1, -1] = 100
print(c)
print(d)

[  0   1   2   3   0   0   0 100]
[0 1 2 3 0 0 0 0]


In [12]:
# Observe que a conversão para array unidimensional pode levar em conta
# a ordem dos elementos na memória
e = a.ravel(order="F")
print("Array e:\n", e)

Array e:
 [  0   0   1   0   2   0   3 100]


In [13]:
# Podemos criar uma nova dimensão em um array já existente através
# da constante np.newaxis
a = np.zeros(6)
b = a[:, np.newaxis]
c = b[:, np.newaxis, :]
print("Formato de a = ", a.shape)
print("Formato de b = ", b.shape)
print("Formato de c = ", c.shape)

Formato de a =  (6,)
Formato de b =  (6, 1)
Formato de c =  (6, 1, 1)


## Funcionalidades de IO

Numpy oferece funcionalidades para salvar dados no sistema de arquivos e recarregá-los de volta.  Isto pode ser feito salvando no modo binário ou no modo texto.  Em modo texto, temos a flexibilidade para salvar em alguns dos formatos mais comuns, como o CSV, por exemplo.

Além destas funcionalidades básicas do Numpy, a biblioteca Scipy também oferece funções para salvar e recuperar dados que são ainda mais poderosas.  Estudaremo-nas quando estudarmos Scipy.

In [14]:
# Podemos salvar em binário um array de cada vez com a função save().  Esta
# função aceita um objeto que se comporte como um File ou uma string
# com o nome do arquivo.  Se for uma string, o sufixo ".npy" é 
# colocado no final do nome, se ainda não existir
import numpy as np
from pathlib import Path

a = np.random.randn(5, 10)

with Path("teste_save.npy").open("wb") as f:
    np.save(f, a)

with Path("teste_save.npy").open("rb") as f:
    b = np.load(f)

print("Array a:", a)
print("Array b:", b)

Array a: [[-0.11824673  1.08872615 -1.40977037 -0.07851572 -1.52813633 -0.18790181
   0.07579842  1.50244966  0.50176295  0.97501869]
 [-0.0927194  -1.58105045 -0.43810949  0.1364422   1.21274265  0.37791728
  -0.46480842  0.43557403 -0.29657564 -0.0118546 ]
 [ 0.69244788  0.5075959   1.48584491 -0.17823643 -0.12242632  0.64544072
  -1.10514712  0.73256198  1.63039365  0.83587056]
 [-1.32697325  0.81474188  0.06915319 -1.95700262 -0.50775429  0.82238197
  -0.57906073 -0.95437626 -0.39995623 -2.01419422]
 [ 0.31305307 -1.03157526 -1.40737392 -1.00019784 -1.30412396  1.51707821
   0.2639414  -2.04989886  0.67723528 -0.90950117]]
Array b: [[-0.11824673  1.08872615 -1.40977037 -0.07851572 -1.52813633 -0.18790181
   0.07579842  1.50244966  0.50176295  0.97501869]
 [-0.0927194  -1.58105045 -0.43810949  0.1364422   1.21274265  0.37791728
  -0.46480842  0.43557403 -0.29657564 -0.0118546 ]
 [ 0.69244788  0.5075959   1.48584491 -0.17823643 -0.12242632  0.64544072
  -1.10514712  0.73256198  1.630

In [15]:
# Para salvar um array em texto, usamos a função savetxt().  Para
# ler um array de um arquivo texto, use a função loadtxt()
a = np.random.randn(5, 10)

with open("teste_save2.dat", "wt") as f:
    np.savetxt(f, a, delimiter=",")

with open("teste_save2.dat", "rt") as f:
    b = np.loadtxt(f, delimiter=",")

print("Array a:", a)
print("Array b:", b)

Array a: [[-0.56515404  0.15363402 -0.34146204 -2.17501804  0.44736125  0.24285062
   2.22390089 -0.39905195  1.08365862  0.07794863]
 [ 1.83286474 -0.58664392  0.22512543 -2.73536204 -0.19514054  0.53480582
   1.55336359  1.59933807  0.10608287  1.08309926]
 [-0.69138497  0.16030399 -0.17148796 -0.40888685 -0.53168151 -0.35856501
   0.40914497  0.14017612  0.14733472 -1.50673287]
 [-2.21748011 -0.18755446  0.12270697  0.61106618 -0.88893332 -2.68372506
  -0.16957721 -0.16859575 -1.31617509 -0.8321852 ]
 [ 1.49795417 -0.42969649 -0.01944115 -0.36763768  0.33792328 -0.31297274
   0.44953811 -2.09767886 -1.22638997  0.20839828]]
Array b: [[-0.56515404  0.15363402 -0.34146204 -2.17501804  0.44736125  0.24285062
   2.22390089 -0.39905195  1.08365862  0.07794863]
 [ 1.83286474 -0.58664392  0.22512543 -2.73536204 -0.19514054  0.53480582
   1.55336359  1.59933807  0.10608287  1.08309926]
 [-0.69138497  0.16030399 -0.17148796 -0.40888685 -0.53168151 -0.35856501
   0.40914497  0.14017612  0.147

In [16]:
# A função loadtxt() também é conveniente para ler arquivos csv.
# Para isso devemos usar o argumento delimiter
with open("scope.csv", "rt") as f:
    a = np.loadtxt(f, delimiter=",", skiprows=2)

print("Formato de a:", a.shape)
print("Conteúdo parcial de a = ", a[:10,:])

Formato de a: (1999, 2)
Conteúdo parcial de a =  [[-0.0256     -0.00125   ]
 [-0.025575    0.00035804]
 [-0.02555    -0.00044598]
 [-0.025525   -0.00285804]
 [-0.0255      0.00035804]
 [-0.025475   -0.00205402]
 [-0.02545    -0.00125   ]
 [-0.025425    0.00196608]
 [-0.0254      0.00035804]
 [-0.025375    0.00035804]]
